// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID                    pgtype.UUID      `json:"id"`
	AccountID             string           `json:"account_id"`
	SessionTokenEncrypted []byte           `json:"session_token_encrypted"`
	SessionTokenHash      string           `json:"session_token_hash"`
	ExpiresAt             pgtype.Timestamp `json:"expires_at"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}
