// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSessionByHash(ctx context.Context, sessionTokenHash string) error
	GetSessionByHash(ctx context.Context, sessionTokenHash string) (Session, error)
}

var _ Querier = (*Queries)(nil)
