// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    account_id,
    session_token_encrypted,
    session_token_hash,
    expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, account_id, session_token_encrypted, session_token_hash, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	AccountID             string           `json:"account_id"`
	SessionTokenEncrypted []byte           `json:"session_token_encrypted"`
	SessionTokenHash      string           `json:"session_token_hash"`
	ExpiresAt             pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AccountID,
		arg.SessionTokenEncrypted,
		arg.SessionTokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SessionTokenEncrypted,
		&i.SessionTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByHash = `-- name: DeleteSessionByHash :exec
DELETE FROM sessions
WHERE session_token_hash = $1
`

func (q *Queries) DeleteSessionByHash(ctx context.Context, sessionTokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByHash, sessionTokenHash)
	return err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, account_id, session_token_encrypted, session_token_hash, expires_at, created_at, updated_at FROM sessions
WHERE session_token_hash = $1
AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetSessionByHash(ctx context.Context, sessionTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, sessionTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SessionTokenEncrypted,
		&i.SessionTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
