// Code generated by mockery. DO NOT EDIT.
package mocks

import (
	context "context"

	ibkr "github.com/majidmvulle/ibkr-client/ibkr-go/internal/ibkr"
	mock "github.com/stretchr/testify/mock"
)

// MockIBKRClient is an autogenerated mock type for the ClientInterface type
type MockIBKRClient struct {
	mock.Mock
}

func (m *MockIBKRClient) Ping(ctx context.Context) error {
	ret := m.Called(ctx)
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (m *MockIBKRClient) AuthStatus(ctx context.Context) (*ibkr.AuthStatusResponse, error) {
	ret := m.Called(ctx)
	var r0 *ibkr.AuthStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*ibkr.AuthStatusResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *ibkr.AuthStatusResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ibkr.AuthStatusResponse)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (m *MockIBKRClient) Reauthenticate(ctx context.Context) error {
	ret := m.Called(ctx)
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (m *MockIBKRClient) GetAccounts(ctx context.Context) ([]ibkr.Account, error) {
	ret := m.Called(ctx)
	var r0 []ibkr.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]ibkr.Account, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []ibkr.Account); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ibkr.Account)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (m *MockIBKRClient) GetPortfolio(ctx context.Context) ([]ibkr.Position, error) {
	ret := m.Called(ctx)
	var r0 []ibkr.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]ibkr.Position, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []ibkr.Position); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ibkr.Position)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (m *MockIBKRClient) GetAccountSummary(ctx context.Context) (*ibkr.AccountSummary, error) {
	ret := m.Called(ctx)
	var r0 *ibkr.AccountSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*ibkr.AccountSummary, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *ibkr.AccountSummary); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ibkr.AccountSummary)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (m *MockIBKRClient) PlaceOrder(ctx context.Context, order *ibkr.OrderRequest) (*ibkr.OrderResponse, error) {
	ret := m.Called(ctx, order)
	var r0 *ibkr.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ibkr.OrderRequest) (*ibkr.OrderResponse, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ibkr.OrderRequest) *ibkr.OrderResponse); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ibkr.OrderResponse)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, *ibkr.OrderRequest) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (m *MockIBKRClient) ModifyOrder(ctx context.Context, orderID string, order *ibkr.OrderRequest) (*ibkr.OrderResponse, error) {
	ret := m.Called(ctx, orderID, order)
	var r0 *ibkr.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *ibkr.OrderRequest) (*ibkr.OrderResponse, error)); ok {
		return rf(ctx, orderID, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *ibkr.OrderRequest) *ibkr.OrderResponse); ok {
		r0 = rf(ctx, orderID, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ibkr.OrderResponse)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, *ibkr.OrderRequest) error); ok {
		r1 = rf(ctx, orderID, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (m *MockIBKRClient) CancelOrder(ctx context.Context, orderID string) error {
	ret := m.Called(ctx, orderID)
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

func (m *MockIBKRClient) GetOrder(ctx context.Context, orderID string) (*ibkr.Order, error) {
	ret := m.Called(ctx, orderID)
	var r0 *ibkr.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ibkr.Order, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ibkr.Order); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ibkr.Order)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (m *MockIBKRClient) ListOrders(ctx context.Context) ([]ibkr.Order, error) {
	ret := m.Called(ctx)
	var r0 []ibkr.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]ibkr.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []ibkr.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ibkr.Order)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (m *MockIBKRClient) SearchContracts(ctx context.Context, symbol string) ([]ibkr.Contract, error) {
	ret := m.Called(ctx, symbol)
	var r0 []ibkr.Contract
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]ibkr.Contract, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []ibkr.Contract); ok {
		r0 = rf(ctx, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ibkr.Contract)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (m *MockIBKRClient) GetMarketData(ctx context.Context, conIDs []int, fields []string) ([]ibkr.MarketDataSnapshot, error) {
	ret := m.Called(ctx, conIDs, fields)
	var r0 []ibkr.MarketDataSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int, []string) ([]ibkr.MarketDataSnapshot, error)); ok {
		return rf(ctx, conIDs, fields)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int, []string) []ibkr.MarketDataSnapshot); ok {
		r0 = rf(ctx, conIDs, fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ibkr.MarketDataSnapshot)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, []int, []string) error); ok {
		r1 = rf(ctx, conIDs, fields)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (m *MockIBKRClient) GetHistoricalData(ctx context.Context, conID int, period, barSize string) (*ibkr.HistoricalData, error) {
	ret := m.Called(ctx, conID, period, barSize)
	var r0 *ibkr.HistoricalData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) (*ibkr.HistoricalData, error)); ok {
		return rf(ctx, conID, period, barSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) *ibkr.HistoricalData); ok {
		r0 = rf(ctx, conID, period, barSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ibkr.HistoricalData)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, int, string, string) error); ok {
		r1 = rf(ctx, conID, period, barSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}
